---
- name: Install Development Tools for Ruby
  hosts: localhost

  vars:
    asdf_user: "{{ ansible_user_id }}"
    asdf_group: "{{ ansible_user_id }}"
    asdf_dir: "/home/{{ ansible_user_id }}/.asdf"
    asdf_plugins:
      - name: ruby
        versions: ["3.1.2"]
        global: "3.1.2"
  roles:
    - cimon-io.asdf